# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Huon d'Auvergne Digital Archive
description: "The Huon d'Auvergne Digital Archive publishes for the first time
all four extant Franco-Italian manuscripts of the Huon d'Auvergne romance-epic."
tagline: "A digital edition of Huon d'Auvergne, a pre-modern, Franco-Italian Epic"
baseurl: "" #add in later in deployment: /hda
url: "" #add in later in deployment in deploytment: http:huondauvergne.org

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-iiif

include: _pages

iiif_allowablefields:
  - label
  - description
  - attribution
  - logo

collections:
  p-images:
    title: "Padua, Biblioteca del seminario vescovile, MS 32"
    output: true
    iiif: true
    paged: true
    fields:
      label: "Franco-Italian Huon d'Auvergne as conserved in Padua, Biblioteca del seminario vescovile, MS 32"
      description: "Pauda Edition"
      attribution: "jekyll-iiif demo"
      logo: "logo.jpg"
  br-images:
        title: "Barbieri, Biblioteca del seminario vescovile, MS 32"
        output: true
        iiif: true
        paged: true
        fields:
          label: "Franco-Italian Huon d'Auvergne-Barbieri, Biblioteca del seminario vescovile, MS 32"
          description: "Barbieri Edition"
          attribution: "jekyll-iiif demo"
          logo: "logo.jpg"

  iiif_images:
    title: "Images"
    output: true
    iiif: true

defaults:
  - scope:
      path: ""
      type: iiif_collection
    values:
      layout: iiif_image

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
