# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Huon d'Auvergne Digital Archive
description: "The Huon d'Auvergne Digital Archive publishes for the first time
all four extant Franco-Italian manuscripts of the Huon d'Auvergne romance-epic."
tagline: "A digital edition of Huon d'Auvergne, a pre-modern, Franco-Italian Epic."
baseurl: "" #add in later in deployment: /hda
url: "" #add in later in deployment in deploytment: http:huondauvergne.org

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include: _pages

gems:
  - jekyll-feed
  - jekyll-iiif

iiif_allowablefields:
  - label
  - description
  - attribution
  - logo

collections:
  narrenschiff:
    title: "Narrenschiff"
    output: true
    iiif: true
    paged: true
    fields:
      label: "Sebastian Brant, Aff-ghebeelde narren speel-schuyt, verciert met meer als hondert schoone figueren nae den aerdt van veelderley sotten die op aerden syn: bewesen met stichtelijcke exempelen, so uyt de H. Schrift als oock uyt de kerckelijcke oudt-vaders ende andere schrijvers meer, tot dienste van een yegelijcken"
      description: "Ghedruckt tot Leyden : By Henrick Lodewicxsz. van Haestens"
      attribution: "jekyll-iiif demo"
      logo: "logo.jpg"

  iiif_images:
    title: "Images"
    output: true
    iiif: true

defaults:
  - scope:
      path: ""
      type: iiif_collection
    values:
      layout: iiif_image

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
